name: Unit tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      GIT_NAME: volto-separator-block
      NAMESPACE: '@kitconcept'
      GIT_USER: 'kitconcept'
    steps:
      - name: Main checkout
        uses: actions/checkout@v2

      # node setup
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      # node install
      - name: Install dependencies
        run: yarn install

      - name: Install yo and @plone/generator-volto
        run: npm i -g yo @plone/generator-volto

      - name: Setup addon testing environment
        run: npx -p @plone/scripts addon clone .

      # Unit tests
      - name: Unit tests
        run: cd addon-testing-project && CI=true yarn test
